// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCte4big1sWvGUVt3BzfS6qNnTTWPCqm9Q',
    appId: '1:818036177141:web:d42e8a0a87bfbffb7eedbc',
    messagingSenderId: '818036177141',
    projectId: 'callejea-cbca4',
    authDomain: 'callejea-cbca4.firebaseapp.com',
    storageBucket: 'callejea-cbca4.appspot.com',
    measurementId: 'G-RV7JSLN6E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeab5VpsoIJhd36_kPHgr587RGXsS8rIM',
    appId: '1:818036177141:android:5436713a927254907eedbc',
    messagingSenderId: '818036177141',
    projectId: 'callejea-cbca4',
    storageBucket: 'callejea-cbca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr818xVfBwO-f95r2CxSEj2hpX7XcqlZQ',
    appId: '1:818036177141:ios:4ea57bc30d3787107eedbc',
    messagingSenderId: '818036177141',
    projectId: 'callejea-cbca4',
    storageBucket: 'callejea-cbca4.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr818xVfBwO-f95r2CxSEj2hpX7XcqlZQ',
    appId: '1:818036177141:ios:5b87b2d79ee034697eedbc',
    messagingSenderId: '818036177141',
    projectId: 'callejea-cbca4',
    storageBucket: 'callejea-cbca4.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
